### ISSUE TITLE
关于model的热替换

### ISSUE THREAD

**Issue by javaLuo** [nanxiaobei/retalk#1]
Hi, 我遇到一个小问题，不知道该怎么配置

现在我引入了retalk, 于是state/action/reducer都写到了model中
store简化如下：
```
import { createStore } from "retalk";

import ModelApp from '../models/app';
import ModelTest from '../models/test';
const store = createStore({
  app: ModelApp,
  test: ModelTest
});

export default store;
```

发现改变model中的代码，不管是action还是reducer，代码会热更新，
但无法触发页面热替换，必须手动F5，才会替换成最新的代码。
我用的是webpack-dev-middleware" 和 "webpack-hot-middleware" 来做的热更新
我该怎么配置呢？

**Comment by nanxiaobei** [comment]
你好，我会测试一下这个问题，如有后续会跟进。

**Comment by nanxiaobei** [comment]
你好，我用 [Create React App](https://github.com/facebook/create-react-app) 建了一个 Demo：https://codesandbox.io/s/5k1467j25x，但是无法复现这个问题。

如还有疑问，可提供一个可复现的 Demo，谢谢。

**Comment by nanxiaobei** [comment]
你好，我又尝试了一下，发现实现热更新的关键是 —— 将 Provider 放在 App.js 中，即获取热更新时，
```js
if (module.hot) {
  module.hot.accept('./App', () => {
    render(App);
  });
}
```
Provider 应在 accept 的 App.js 中，而不能在其外。

**Comment by javaLuo** [comment]
好的 我正在尝试。
无论如何，这不是retalk的问题
非常感谢！

**Comment by javaLuo** [comment]
果然如此
谢大神指点
