### ISSUE TITLE
如何对类似Vuex在A模块操作的B模块的state或是action

### ISSUE THREAD

**Issue by he5050** [nanxiaobei/retalk#11]
如何在A模块里面直接获取B模块的state，或是操作B模块里的action。我现在使用的是eventBus来做，或是要A模块引入store/index.js，然后使用store.getState()来做，有没有别的方式？

**Comment by nanxiaobei** [comment]
1. a 模块的 action 中，直接通过 this.b.state 可以拿到 b 的 state。
2. 不提供直接在线a 模块 action 中调用 this.b.setState，建议在 b 中加入相应 action，然后 a 中调用 this.b.someAction。

**Comment by he5050** [comment]
好的，谢谢大佬
