### ISSUE TITLE
Redux DevTools  可以自定义使用不?

### ISSUE THREAD

**Issue by he5050** [nanxiaobei/retalk#13]
V3版本的DevTools 可以自行配置启用

**Comment by nanxiaobei** [comment]
目前非 `production` 环境下会自动启用，不支持手动关闭。
如果想关闭的话 ... 那不看 Redux DevTools 就行了。 😑

**Comment by he5050** [comment]
希望可以手动支持，有些特殊情况下，需要在生产环境下了看一些数据
