### ISSUE TITLE
怎么引入插件

### ISSUE THREAD

**Issue by he5050** [nanxiaobei/retalk#3]
比如引入redux-logger

**Comment by nanxiaobei** [comment]
稍后会加上，请稍等

**Comment by he5050** [comment]
redux-devtools 如何引入？

**Comment by nanxiaobei** [comment]
redux-devtools 可以这样来使用 `createStore(models, true)`：https://github.com/nanxiaobei/retalk#createstore，但是得保证其版本  >= 2.15.3

**Comment by he5050** [comment]
谢谢，我的问题

**Comment by he5050** [comment]
ssr 不支持嘛？

**Comment by nanxiaobei** [comment]
暂未测试过 ssr 相关支持，可以参考这里：https://redux.js.org/recipes/serverrendering

**Comment by he5050** [comment]
蓝小北同学 什么更新可以使用插件或是自定义插件

**Comment by nanxiaobei** [comment]
可能就在这周吧，因为最近比较忙，还没时间抽空去做这块~

**Comment by nanxiaobei** [comment]
你好，

Retalk 已经升级到 v1.2.0，现在可以引入插件了，注意使用 Redux DevTools 的方式也变了，

具体看这里：https://github.com/nanxiaobei/retalk#createstore
