### ISSUE TITLE
关于retalk的store持久化

### ISSUE THREAD

**Issue by chaozhang5** [nanxiaobei/retalk#6]
Hi, 大佬，这边在写demo时遇到了个问题
在使用retalk存储store数据的时候如何将store数据持久化，结合redux-persist使用发现会有问题，有没有什么好的建议呢
store如下
import { createStore } from 'retalk';
import IndexModel from '../models/index';
import UserModel from '../models/user';

const store = createStore({
	IndexModel,
        UserModel
})

export default store;

userModel如下
const model = {
	/** store数据 **/
	state: {
		userInfo: {}
	},

	/** actions **/
	actions: {
		// 模拟用户登录
    async login(params = {}) {
      const user = { id: params.id, username: params.username };
      this.setState({ userInfo: user });
      return user;
    },

    // 模拟用户退出
    async loginOut(params = {}) {
      this.setState({ userInfo: {} });
      return {};
    }
	}
}

export default model;
现在想实现将用户信息持久化存储，该如何实现

**Comment by nanxiaobei** [comment]
你好，我看了下 redux-persist 的使用方式，需要使用 persistReducer 包裹 rootReducer，retalk 未暴露 rootReducer 给外部，所以可能无法与 redux-persist 兼容。

**Comment by he5050** [comment]
@chaozhang5 可以简单的试试这种方式
```javascript
// 写个简单那的中间件，把每次更新后的状态存到storage里面，当然后这里你可以做个节流处理
const persist = store => next => action => {
    console.log(action);
    next(action);
    console.log(store.getState());
    sessionStorage.setItem("store", JSON.stringify(store.getState()));
};
```
```javascript
//初始化的时候
let initData = {};
if (!!process.browser && sessionStorage && sessionStorage.getItem("store")) {
    const store = JSON.parse(sessionStorage.getItem("store") || "{}");
    for (const key in store) {
        if (store[key].hasOwnProperty("loading")) {
            delete store[key]["loading"];
        }
        initData[key] = {
            state: store[key]
        };
    }
}
```
后面的你就可以model里面进行初始化或是别的操作就看自己了的

**Comment by he5050** [comment]
@chaozhang5  补充一下，第一次的时候是没有这个值，所以你在这里要做判断
