### ISSUE TITLE
貌似无法支持IE呀

### ISSUE THREAD

**Issue by javaLuo** [nanxiaobei/retalk#7]
hi,大佬
我看见retalk的源代码里使用了new Proxy
而IE11不支持Proxy, 我自己的项目编译后在IE下会报“Proxy未定义”..
我应该安装什么polyfill吗

**Comment by nanxiaobei** [comment]
你好，可以试下这个：https://github.com/GoogleChrome/proxy-polyfill

**Comment by javaLuo** [comment]
好的 thanks
