### ISSUE TITLE
只支持函数组件？换成类组件报错！

### ISSUE THREAD

**Issue by lilian132** [nanxiaobei/retalk#8]
把View里面的demo函数组件换成类组件就报错，写法如下：

`import React, { Component } from 'react';
import { connect } from "react-redux";
import { withStore } from "retalk";

class Demo extends Component {
    constructor(props) {
        super(props);
        console.log(this.props)
    }
    render(){
        return (
            ......
        )
    }
}

export default connect(...withStore("demo"))(Demo);`

错误：exports is not defined

**Comment by lilian132** [comment]
自己找了下原因，很诡异
connect(...withStore("demo")) 用了...运算符就会报错，
connect(withStore("demo")[0], withStore("demo")[1])不会报错

**Comment by nanxiaobei** [comment]
你好，我试了一下，没有报错：https://codesandbox.io/s/2o8xnmzj5n

**Comment by lilian132** [comment]
> 你好，我试了一下，没有报错：https://codesandbox.io/s/2o8xnmzj5n

应该是我项目其它地方影响到了，谢谢
